### ISSUE TITLE
Please add support for JavaScript

### ISSUE THREAD

**Issue by paulvi** [henri5/completeline#3]
Awesome, this plugins adds `{}` when needed

```
for(int i=1; i<=10; i++)
```

->

```
for(int i=1; i<=10; i++){
    _
}
```

Please do the same for JavaScript

```
for(i=1; i<=10; i++)
```

**Comment by henri5** [comment]
If you add the same command to also be used when Editing Javascript Source from _Preferences > General > Keys_
![image](https://cloud.githubusercontent.com/assets/6851758/12751866/3b4b1c70-c9c8-11e5-9ecb-d4937d04c2a3.png)
then this particular use case will work. However I'll need to first test how other line completion actions behave with JS code before enabling it by default.

**Comment by paulvi** [comment]
Oh, interesting, I should try this.

By the way `Preferences > General > Keys` can be opened with double Ctrl+Shift+L

**Comment by paulvi** [comment]
Currently for JS it makes worse: it add empty line before and move cursor before that line.

It should at least not add anything before, and do not move in position before current position.

**Comment by henri5** [comment]
I added the keybinding for JavaScript editor by default and fixed this particular issue with curly brackets getting inserted before the statement. But I didn't test much beyond that and hope it mostly works already because JS and Java syntax are quite similar. Should you find any other issues where the completion works very wrong for JS (compared to Java), let me know and I'll see if I can fix it.
